In [1]:
# Standard imports

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# Fit the model / algorithm on our data and use it to make a prediction

### 3.1 Fit the model to the data


Different names for:

* `X = features, feature variables, Data`

* `y = labels, targets, target variables`

In [3]:
heart_disease = pd.read_csv('C:/Users/gthom/sample_project/Data/heart-disease.csv')

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

# set up random seed
np.random.seed(42)

# Create the data

X = heart_disease.drop('target', axis=1)
y = heart_disease['target']

# Split the data

X_test, X_train, y_test, y_train = train_test_split(X, y, test_size=0.2)

# Instatiate RandomForest

clf = RandomForestClassifier()

# Fit the model to the Data (training the machine learning model)

clf.fit(X_train, y_train)

# Evaluate the RandomForest Classifier (use the patterns the model has learned)

clf.score(X_test, y_test)

0.7892561983471075

In [6]:
X.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [7]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

### 3.2 Make predictions using a machine learning model

The 2 main ways for prediction:

1. `predict()`
2. `predict_proba()`

#### Use a trained model to predict

In [8]:
clf.predict(X_test)

array([1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1],
      dtype=int64)

In [10]:
np.array(y_test)

array([1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1],
      dtype=int64)

##### Compare predictions to truth labels to evaluate the model

In [12]:
y_preds = clf.predict(X_test)
np.mean(y_preds == y_test)

0.7892561983471075

In [13]:
clf.score(X_test, y_test)

0.7892561983471075

In [14]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_preds)

0.7892561983471075

#### Make predictions using `predict_proba()`

In [15]:
# predict_proba() returns probabilities of a classification label

clf.predict_proba(X_test)

array([[0.07, 0.93],
       [0.81, 0.19],
       [0.21, 0.79],
       [0.19, 0.81],
       [0.7 , 0.3 ],
       [0.3 , 0.7 ],
       [0.28, 0.72],
       [0.39, 0.61],
       [0.15, 0.85],
       [0.04, 0.96],
       [0.18, 0.82],
       [0.48, 0.52],
       [0.09, 0.91],
       [0.81, 0.19],
       [0.03, 0.97],
       [0.14, 0.86],
       [0.37, 0.63],
       [0.65, 0.35],
       [0.45, 0.55],
       [0.12, 0.88],
       [0.89, 0.11],
       [0.41, 0.59],
       [0.23, 0.77],
       [0.33, 0.67],
       [0.63, 0.37],
       [0.93, 0.07],
       [0.3 , 0.7 ],
       [0.35, 0.65],
       [0.31, 0.69],
       [0.27, 0.73],
       [0.02, 0.98],
       [0.04, 0.96],
       [0.08, 0.92],
       [0.35, 0.65],
       [0.12, 0.88],
       [0.49, 0.51],
       [0.68, 0.32],
       [0.  , 1.  ],
       [0.48, 0.52],
       [0.2 , 0.8 ],
       [0.07, 0.93],
       [0.23, 0.77],
       [0.7 , 0.3 ],
       [0.41, 0.59],
       [0.01, 0.99],
       [0.12, 0.88],
       [0.21, 0.79],
       [0.49,

In [16]:
clf.predict_proba(X_test[:5])

array([[0.07, 0.93],
       [0.81, 0.19],
       [0.21, 0.79],
       [0.19, 0.81],
       [0.7 , 0.3 ]])

In [17]:
# Let's predict on the same data...

In [18]:
clf.predict(X_test[:5])

array([1, 0, 1, 1, 0], dtype=int64)

In [21]:
X_test[:5]

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
132   42    1   1       120   295    0        1      162      0      0.0   
202   58    1   0       150   270    0        0      111      1      0.8   
196   46    1   2       150   231    0        1      147      0      3.6   
75    55    0   1       135   250    0        0      161      0      1.4   
176   60    1   0       117   230    1        1      160      1      1.4   

     slope  ca  thal  
132      2   0     2  
202      2   0     3  
196      1   0     2  
75       1   0     2  
176      2   2     3

####  `predict( )` can also be used for Regression models

In [ ]:
from sklearn.ensemble import RandomForestRegressor

np.random.seed(42)

# Create the data

boston_df = pd.read_csv('C:/Users/gthom/sample_project/Data/heart-disease.csv')

X = boston_df.drop('target', axis=1)
y = boston_df['']